name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add GitHub to known_hosts
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Add server to known_hosts
        run: |
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy files via SCP
        run: |
          scp -r ./* user@${{ secrets.SERVER_IP }}:/home/wellbing/notification

      - name: Install dependencies and restart app
        run: |
          ssh user@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/wellbing/notification
            npm install
            pm2 restart all || pm2 start app.js
          EOF
